CREATE TABLE IF NOT EXISTS agent_enrollment_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Optional pre-auth metadata; agent_auth.uid is the canonical authenticated identity.
    uid character varying(64),
    hostname character varying(255) NOT NULL,
    fqdn character varying(255),
    os_type character varying(50),
    agent_version text,
    request_ip inet NOT NULL,

    -- Visual display code shown on the enrolling host console and in the admin UI.
    -- Display-only; not an authentication factor. Auth is poll_token + request_id
    -- for the installer polling session, and admin UI access control + CSRF token
    -- for the approval action.
    pairing_code text,
    pairing_code_hash text NOT NULL,
    pairing_code_hash_algorithm text NOT NULL DEFAULT 'hmac-sha256',
    -- Poll token authenticates the installer polling session.
    poll_token_hash text NOT NULL,
    poll_token_hash_algorithm text NOT NULL DEFAULT 'hmac-sha256',

    status text NOT NULL DEFAULT 'pending',
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP + interval '30 minutes',
    last_poll_at timestamptz,

    approved_at timestamptz,
    approved_by text,
    denied_at timestamptz,
    denied_by text,
    denial_reason text,
    -- Reason for expiry, e.g. replaced_by_new_request, timeout, admin_action.
    expired_reason text,
    used_at timestamptz,

    CONSTRAINT chk_agent_enrollment_requests_status
        CHECK (status IN ('pending', 'approved', 'used', 'denied', 'expired'))
);

COMMENT ON COLUMN agent_enrollment_requests.pairing_code IS
    'Visual display code shown on the enrolling host console and in the admin UI. '
    'Display-only; not an authentication factor. '
    'Auth is poll_token + request_id for the installer polling session, '
    'and admin UI access control + CSRF token for the approval action.';

CREATE INDEX IF NOT EXISTS idx_agent_enrollment_requests_uid
    ON agent_enrollment_requests (uid);

CREATE INDEX IF NOT EXISTS idx_agent_enrollment_requests_status_created_at
    ON agent_enrollment_requests (status, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_enrollment_requests_expires_at
    ON agent_enrollment_requests (expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_enrollment_requests_active_pairing_code_hash
    ON agent_enrollment_requests (pairing_code_hash)
    WHERE status IN ('pending', 'approved');

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_enrollment_requests_one_pending_per_host
    ON agent_enrollment_requests (request_ip, lower(hostname))
    WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS agent_auth (
    uid character varying(64) PRIMARY KEY,

    agent_secret_hash text NOT NULL,
    agent_secret_hash_algorithm text NOT NULL DEFAULT 'hmac-sha256',
    secret_issued_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    secret_last_rotated_at timestamptz,

    created_from_enrollment_request_id bigint
        REFERENCES agent_enrollment_requests (id)
        ON DELETE SET NULL,

    status text NOT NULL DEFAULT 'active',
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    last_auth_at timestamptz,
    last_inventory_at timestamptz,

    disabled_at timestamptz,
    disabled_by text,
    disabled_reason text,
    revoked_at timestamptz,
    revoked_by text,
    revoked_reason text,

    CONSTRAINT chk_agent_auth_status
        CHECK (status IN ('active', 'disabled', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_agent_auth_status
    ON agent_auth (status);

CREATE INDEX IF NOT EXISTS idx_agent_auth_created_from_enrollment_request_id
    ON agent_auth (created_from_enrollment_request_id);

CREATE INDEX IF NOT EXISTS idx_agent_auth_last_auth_at
    ON agent_auth (last_auth_at);

CREATE INDEX IF NOT EXISTS idx_agent_auth_disabled_at
    ON agent_auth (disabled_at)
    WHERE disabled_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_auth_revoked_at
    ON agent_auth (revoked_at)
    WHERE revoked_at IS NOT NULL;
