CREATE TABLE IF NOT EXISTS agent_auth_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    uid character varying(64) NOT NULL,
    agent_secret_hash text NOT NULL,
    agent_secret_hash_algorithm text NOT NULL DEFAULT 'hmac-sha256',
    secret_issued_at timestamptz,
    secret_last_rotated_at timestamptz,

    created_from_enrollment_request_id bigint
        REFERENCES agent_enrollment_requests (id)
        ON DELETE SET NULL,
    replacement_enrollment_request_id bigint
        REFERENCES agent_enrollment_requests (id)
        ON DELETE SET NULL,

    status text NOT NULL,
    created_at timestamptz,
    updated_at timestamptz,
    last_auth_at timestamptz,
    last_inventory_at timestamptz,

    disabled_at timestamptz,
    disabled_by text,
    disabled_reason text,
    revoked_at timestamptz,
    revoked_by text,
    revoked_reason text,

    archived_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_reason text NOT NULL
);

COMMENT ON TABLE agent_auth_history IS
    'Audit-only archive of superseded or safely cleaned up agent_auth rows. Never used for authentication.';

CREATE INDEX IF NOT EXISTS idx_agent_auth_history_uid
    ON agent_auth_history (uid);

CREATE INDEX IF NOT EXISTS idx_agent_auth_history_created_from_enrollment_request_id
    ON agent_auth_history (created_from_enrollment_request_id);

CREATE INDEX IF NOT EXISTS idx_agent_auth_history_replacement_enrollment_request_id
    ON agent_auth_history (replacement_enrollment_request_id);

CREATE INDEX IF NOT EXISTS idx_agent_auth_history_archived_at
    ON agent_auth_history (archived_at);
