# Allowed protocols
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;

# Allowed ciphers
ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';

# ECDH curve
ssl_ecdh_curve secp384r1;

# session cache
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;

# ocsp stapling
ssl_stapling on;
ssl_stapling_verify on;
    # resolver 127.0.0.1 valid=300s;  # Optional: set your local DNS resolver if OCSP stapling verification needs it.
resolver_timeout 5s;

# Security headers
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options nosniff always;
add_header Referrer-Policy "no-referrer-when-downgrade" always;

# Diffie-Hellman parameters
ssl_dhparam /etc/nginx/dhparam2048.pem;

